### ISSUE TITLE
Code in chapter 4 not matching content in book

### ISSUE THREAD

**Issue by marcus-franzen** [PacktPublishing/Isomorphic-JavaScript-Web-Development#2]
The package.json is not reflecting the content in the book, e.g. 

"webpack-dev-middleware": "github:koistya/Webpack-dev-middleware",
 "webpack-hot-middleware": "^2.21.0"

is missing and github:koistya/Webpack-dev-middleware is also not running with 

"webpack": "^3.5.6",

which is referenced in the book.

Couldn't get it running as it is in the book, wondering if I should continue working on the examples if such obvious errors are in there.

**Comment by tomasAlabes** [comment]
Hi @marcus-franzen, thank you for noticing this, we are sorry you faced this issue.

I've merged the fix using the official `webpack-dev-middleware` package. You should be able to run
```
npm install
npm run build
npm run serve
```

Please let us know if you see anything else wrong. I will take this to the publishers.
Thank you
