### ISSUE TITLE
serve/build not working

### ISSUE THREAD

**Issue by marko911** [PacktPublishing/Isomorphic-JavaScript-Web-Development#3]
I cloned the code of the repo and when I try to run `npm run serve` it cannot find the build/server.js file. Maybe a faulty build script? Also, the copying task doesn't finish, it just says 'starting copy' and then just spits out undefined.

**Comment by tomasAlabes** [comment]
Hi @marko911, what chapter? Did you run `npm run build`?

I will review the code here soon because I think some things weren't incorrectly uploaded. Sorry for the inconvenience.

**Comment by marko911** [comment]
I pulled the repo and did npm install, tried npm rub build and it returned undefined after starting "Copy" task. It didnt finish that task. 
  Edit: Did this for ch1 and 2 , same result

**Comment by tomasAlabes** [comment]
Just needed to create the `build` directory first. Added that to the code. Thanks for noticing it!

**Comment by marko911** [comment]
Thanks for the fix. But there are still issues regarding this repo aligning with the book. For example, the serve task states from the book that since watch is enabled, when running serve any changes to the code should rebuild and restart the server but when doing it with your latest code, this doesnt happen. Can you sync the process the book goes through with the code in the repo?

**Comment by tomasAlabes** [comment]
I will contact the Packt to see if we can modify the book content to match the code. The first chapters In particular weren't written by me but I will take over if it's necessary.
The code here now might be slightly better / more modern than the book's.
