### ISSUE TITLE
 I have a question about the basic isomorphic router implementation.

### ISSUE THREAD

**Issue by chbaefront** [PacktPublishing/Isomorphic-JavaScript-Web-Development#5]
![image](https://user-images.githubusercontent.com/46551736/88487095-36993400-cfbd-11ea-82cf-9177491f77d3.png)

ReferenceError: location is not defined

How should I handle this error?
I want to know how this error occurs because my code and example code are different.

```
import React from 'react';

export default function Header() {

    function goPage(path) {
        console.log(location); // error
        // window.location = path;
    }

    return (
        <header style={{width: '100%', border: '1px dotted black'}}>
            <div>
                <span style={{padding: '4px'}}>My App |</span>
                <span style={{padding: '4px', cursor: 'pointer'}}>Home</span>
                <span style={{padding: '4px', cursor: 'pointer'}} onClick={goPage('/about')}>About</span>
            </div>
        </header>
    )
}
```

my code : https://github.com/katanazero86/isomorphic-web

**Comment by tomasAlabes** [comment]
`location` is not defined at the moment you want to `console.log` it, try with 
```
console.log(window.location);
```

**Comment by chbaefront** [comment]
In the chater 2 code, why am I getting an error when using the location object?
